import { Exercise, BodyType, Gender, Difficulty } from './types';

export const exercisesData: Omit<Exercise, 'id' | 'created_at'>[] = [
  // Chest exercises
  {
    name: 'Supino Reto com Barra',
    description: 'Exercício fundamental para desenvolvimento do peitoral.',
    instructions: '1. Deite no banco com os pés firmes no chão.\n2. Segure a barra com pegada um pouco mais larga que os ombros.\n3. Desça a barra controladamente até tocar o peito.\n4. Empurre a barra para cima até estender os braços.',
    muscle_group: 'chest',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '8-12',
  },
  {
    name: 'Supino Inclinado com Halteres',
    description: 'Foco na parte superior do peitoral.',
    instructions: '1. Ajuste o banco em 30-45 graus.\n2. Segure os halteres na altura do peito.\n3. Empurre os halteres para cima, aproximando-os no topo.\n4. Desça controladamente.',
    muscle_group: 'chest',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '10-12',
  },
  {
    name: 'Flexão de Braços',
    description: 'Exercício clássico para peitoral, ombros e tríceps.',
    instructions: '1. Posicione as mãos na largura dos ombros.\n2. Mantenha o corpo reto da cabeça aos pés.\n3. Desça o peito até quase tocar o chão.\n4. Empurre de volta à posição inicial.',
    muscle_group: 'chest',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '15-20',
  },

  // Back exercises
  {
    name: 'Puxada Frontal',
    description: 'Exercício para desenvolvimento das costas e dorsais.',
    instructions: '1. Sente-se na máquina com as coxas sob o apoio.\n2. Segure a barra com pegada larga.\n3. Puxe a barra até a altura do queixo.\n4. Retorne controladamente.',
    muscle_group: 'back',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '10-12',
  },
  {
    name: 'Remada Curvada',
    description: 'Exercício composto para costas e bíceps.',
    instructions: '1. Segure a barra com pegada pronada.\n2. Incline o tronco a 45 graus.\n3. Puxe a barra até a cintura.\n4. Desça controladamente.',
    muscle_group: 'back',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '8-10',
  },
  {
    name: 'Barra Fixa',
    description: 'Exercício avançado para costas e bíceps.',
    instructions: '1. Segure a barra com pegada pronada.\n2. Pendure-se com os braços estendidos.\n3. Puxe o corpo até o queixo passar a barra.\n4. Desça controladamente.',
    muscle_group: 'back',
    body_type: ['mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'advanced',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '6-10',
  },

  // Shoulders
  {
    name: 'Desenvolvimento com Halteres',
    description: 'Exercício principal para ombros.',
    instructions: '1. Sente-se com as costas apoiadas.\n2. Segure os halteres na altura dos ombros.\n3. Empurre os halteres para cima.\n4. Desça controladamente.',
    muscle_group: 'shoulders',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '10-12',
  },
  {
    name: 'Elevação Lateral',
    description: 'Isolamento do deltóide lateral.',
    instructions: '1. Segure os halteres ao lado do corpo.\n2. Eleve os braços lateralmente até a altura dos ombros.\n3. Mantenha uma leve flexão nos cotovelos.\n4. Desça controladamente.',
    muscle_group: 'shoulders',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '12-15',
  },

  // Biceps
  {
    name: 'Rosca Direta com Barra',
    description: 'Exercício clássico para bíceps.',
    instructions: '1. Segure a barra com pegada supinada.\n2. Mantenha os cotovelos junto ao corpo.\n3. Flexione os cotovelos até a barra chegar aos ombros.\n4. Desça controladamente.',
    muscle_group: 'biceps',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '10-12',
  },
  {
    name: 'Rosca Martelo',
    description: 'Foco no braquial e antebraço.',
    instructions: '1. Segure os halteres com pegada neutra.\n2. Flexione alternadamente.\n3. Mantenha os cotovelos fixos.\n4. Controle o movimento.',
    muscle_group: 'biceps',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '10-12',
  },

  // Triceps
  {
    name: 'Tríceps Pulley',
    description: 'Isolamento do tríceps na polia.',
    instructions: '1. Segure a barra ou corda no pulley.\n2. Mantenha os cotovelos junto ao corpo.\n3. Estenda os braços completamente.\n4. Retorne controladamente.',
    muscle_group: 'triceps',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '12-15',
  },
  {
    name: 'Tríceps Francês',
    description: 'Exercício focado na cabeça longa do tríceps.',
    instructions: '1. Deite no banco segurando a barra EZ.\n2. Estenda os braços acima do peito.\n3. Flexione os cotovelos descendo atrás da cabeça.\n4. Estenda novamente.',
    muscle_group: 'triceps',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '10-12',
  },

  // Legs
  {
    name: 'Agachamento Livre',
    description: 'Rei dos exercícios para pernas.',
    instructions: '1. Posicione a barra nos trapézios.\n2. Pés na largura dos ombros.\n3. Agache até as coxas ficarem paralelas ao chão.\n4. Suba empurrando pelos calcanhares.',
    muscle_group: 'legs',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '8-12',
  },
  {
    name: 'Leg Press',
    description: 'Exercício para quadríceps e glúteos.',
    instructions: '1. Posicione os pés na plataforma.\n2. Destrave a máquina.\n3. Flexione os joelhos até 90 graus.\n4. Empurre de volta.',
    muscle_group: 'legs',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '10-15',
  },
  {
    name: 'Extensão de Pernas',
    description: 'Isolamento do quadríceps.',
    instructions: '1. Sente-se na máquina.\n2. Posicione os pés sob o rolo.\n3. Estenda as pernas completamente.\n4. Desça controladamente.',
    muscle_group: 'legs',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '12-15',
  },
  {
    name: 'Flexão de Pernas',
    description: 'Isolamento dos isquiotibiais.',
    instructions: '1. Deite na máquina de face para baixo.\n2. Posicione os pés sob o rolo.\n3. Flexione as pernas até os calcanhares tocarem os glúteos.\n4. Retorne controladamente.',
    muscle_group: 'legs',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '12-15',
  },

  // Glutes (Female focused)
  {
    name: 'Hip Thrust',
    description: 'Melhor exercício para glúteos.',
    instructions: '1. Apoie as costas em um banco.\n2. Posicione a barra sobre o quadril.\n3. Eleve o quadril contraindo os glúteos.\n4. Desça controladamente.',
    muscle_group: 'glutes',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '10-15',
  },
  {
    name: 'Elevação Pélvica',
    description: 'Exercício para ativação dos glúteos.',
    instructions: '1. Deite de costas com joelhos flexionados.\n2. Eleve o quadril do chão.\n3. Contraia os glúteos no topo.\n4. Desça lentamente.',
    muscle_group: 'glutes',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '15-20',
  },
  {
    name: 'Abdução de Quadril',
    description: 'Foco no glúteo médio.',
    instructions: '1. Sente-se na máquina abdutora.\n2. Posicione as pernas nos apoios.\n3. Abra as pernas contra a resistência.\n4. Retorne controladamente.',
    muscle_group: 'glutes',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '15-20',
  },
  {
    name: 'Kickback no Cabo',
    description: 'Isolamento do glúteo máximo.',
    instructions: '1. Prenda a caneleira no tornozelo.\n2. Apoie-se na máquina.\n3. Estenda a perna para trás.\n4. Retorne controladamente.',
    muscle_group: 'glutes',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '12-15',
  },
  {
    name: 'Agachamento Sumô',
    description: 'Foco em glúteos e adutores.',
    instructions: '1. Pés bem afastados com pontas para fora.\n2. Segure um halter ou kettlebell.\n3. Agache mantendo os joelhos alinhados.\n4. Suba contraindo os glúteos.',
    muscle_group: 'glutes',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['female'],
    difficulty: 'intermediate',
    image_url: null,
    video_url: null,
    sets: 4,
    reps: '10-15',
  },

  // Core
  {
    name: 'Prancha Abdominal',
    description: 'Exercício isométrico para core.',
    instructions: '1. Apoie antebraços e pontas dos pés.\n2. Mantenha o corpo reto.\n3. Contraia o abdômen.\n4. Mantenha a posição.',
    muscle_group: 'core',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '30-60s',
  },
  {
    name: 'Abdominal Crunch',
    description: 'Exercício clássico para abdômen.',
    instructions: '1. Deite com joelhos flexionados.\n2. Mãos atrás da cabeça.\n3. Eleve os ombros do chão.\n4. Desça controladamente.',
    muscle_group: 'core',
    body_type: ['ectomorph', 'mesomorph', 'endomorph'],
    gender: ['male', 'female'],
    difficulty: 'beginner',
    image_url: null,
    video_url: null,
    sets: 3,
    reps: '15-20',
  },
];
